resources:    
  - uri: /
    name: MainResource
    parameters:
      template: main.tpl
      
  - uri: /songs
    name: SongsResource
    parameters:
      template: songs.tpl

  - uri: /projects
    name: MainResource
    parameters:
      template: projects.tpl 

  - uri: /blog
    name: BlogResource
    parameters:
      template: blog.tpl
      
  - uri: /Oregon_Trail_Death
    name: OregonTrailResource
    parameters:
      template: oregon_trail.tpl
      image: oregon_trail_death.jpg
      title: "Oregon Trail Death"
      type: death
      
  - uri: /Oregon_Trail_Disease
    name: OregonTrailResource
    parameters:
      template: oregon_trail.tpl
      image: oregon_trail_disease.jpg
      title: "Oregon Trail Disease"
      type: disease
      
  - uri: /Sitemap.xml
    name: MainResource
    parameters:
      template: sitemap.tpl      
      
  - uri: /robots.txt
    name: MainResource
    parameters:
      template: robots.tpl
 